:Author: leos
:Email: leos@uw.edu
:Date: 07/10/2018
:Revision: version#c
:License: Public Domain

= Project: Arduino-Driven LED Traffic Light

Exercise 0, HCDE 539 Physical Computing, University of Washington
October 7, 2018

== Step 1: Installation

a. Open Tinkercad circuit project at https://www.tinkercad.com/things/bmWjk7KrzkS-arduino-led-traffic-light-modular-code [Arduino LED Traffic Light - Modular Code]
b. Download the code from Tinkercad, upload to your Arduino IDE (desktop or cloud versions should both work).
== Step 2: Assemble the circuit

a. Wire up the Arduino Uno (or Adafruit metro), LED's, resistors, and breadboard as shown in the tinkercad drawing.
b. Also see LeosTinkerCAD_RevC.PNG, included with this sketch.

== Step 3: Load the code

From your Arduino IDE, verifiy the code then upload it to your board.


=== Folder structure

....
 HCDE_539_3O                   => Arduino sketch folder
  ├── HCDE_539_EO.ino -------------=> main Arduino file
  ├── LeosTinkerCAD_RevC.PNG ------=> Tinkercad wiring schematic
  ├── Metro_And_Breadboard.jpg ----=> Finished Product
  ├── MacBook_Metro_Breadboard.jpg => Finished Product with Macbook dev station.
  └── ReadMe.adoc -----------------=> this file
....

=== License
This project is released under a {Attribution 3.0(CC-BY 3.0)} License.

=== Contributing
To contribute to this project please contact leos <leos@uw.edu>

=== BOM
Bill of the materials needed for this project.

|===
| ID | Part name        | Part number | Quantity
| U3 | Adafruit Metro   | 50          | 1 
| D1 | Red LED          | P299B       | 1
| D2 | Yellow LED       | P2700       | 1
| D3 | Green LED        | P298B       | 1
| R  | 200 ohm Resistor | P2780A      | 3        
| A1 | Arduino Zero     | ABX00066    | 1        
|===

=== Further Reading
https://github.com/LeoSalemann/UW_HCDE539/tree/master/Class01/HCDE_539_EO[Github Repo]
https://create.arduino.cc/projecthub/leos/hcde-539-assignment-1-a-3-led-traffic-light-9cd996[Arduino Project Hub]

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
