:Author: leos
:Email: leos@uw.edu
:Date: 14/10/2018
:Revision: version#
:License: Public Domain

= Individual Builds (Sensors, Motors, wiledard)

Leo J.Salemann, leow@uw.edu

Designed and simulated with https://www.tinkercad.com[Autodesk(R) Tinkercad(TM)]

Deployed to Adafruit Metro with https://create.arduino.cc[Ardino Web Editor]

Posted to https://create.arduino.cc/projecthub/projects/9cd996[Arduino Project Hub]

Submitted for Exercise 1, HCDE 539 Physical Computing, University of Washington

October 15, 2018

= Overview
For the initial design and implementation, I created a "Sensor Smorgasbord" project in which I combined all four individual builds onto one bread board, and wrote a single program to run everything.

= Light Sensor
Describe your project

== Photos

== Sketch Code

== Schematic

== Serial Monitor Output

== Problems, Successes Learnings

= Magnetic Sensor
Describe your project

== Photos

== Sketch Code

== Schematic

== Serial Monitor Output

== Problems, Successes Learnings

= Motor
Describe your project

== Photos

== Sketch Code

== Schematic

== Serial Monitor Output

== Problems, Successes Learnings

= Wildcard (POT Party)
Describe your project

== Photos

== Sketch Code

== Schematic

== Serial Monitor Output

== Problems, Successes, Learnings


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
